### ISSUE TITLE
[BUG]: loadFromGithubGist 

### ISSUE THREAD

**Issue by Theigrams** [vipzhicheng/logseq-plugin-global-custom-css#1]
I can't load the css from the Github Gist, I think there might be some mistakes in https://github.com/vipzhicheng/logseq-plugin-global-custom-css/blob/41fb0b71ffa291edc5d1ce10e4635e7351868bc5/src/stores/editor.ts#L55

where `vipzhicheng` may need to be replaced with our user id.

**Comment by vipzhicheng** [comment]
oh, yes, my fault, seems need to add one more setting.
